ports:
  - port: 3001-5000000
    onOpen: ignore
  - port: 1-2999
    onOpen: ignore
image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true