ports:
  - port: 8080
tasks:
  - name : virtualenv
    before: >
      python3 -m venv ~/venv
      echo "source ~/venv/bin/activate" >> ~/.bashrc

image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true