ports:
  - port: 8080
tasks:
  - name : virtualenv
    before: |
      python3 -m venv /workspace/academy-capstone/venv
      echo "source /workspace/academy-capstone/venv/bin/activate" >> ~/.bashrc

image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true