ports:
  - port: 20002
  - port: 4040
image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true