ports:
  - port: 8080
tasks:
  - name: setup
    init: |
      python3 -m venv venv
      source venv/bin/activate
      pip install pyspark
      deactivate
    command: |
      echo "source $(pwd)/venv/bin/activate" >> ~/.bashrc
      source venv/bin/activate
image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
