ports:
  - port: 8080
tasks:
  - name: setup
    init: |
      python3 -m venv venv
      source venv/bin/activate
      pip install pyspark
      deactivate
      # Apply fix for ValueError / AccumulatorServer errors
      #   - https://github.com/gitpod-io/gitpod/issues/7628
      #   - https://github.com/gitpod-io/gitpod/pull/7534
      accs="$(t="venv/lib/python*"; echo $t)/site-packages/pyspark/accumulators.py"
      sed -i "s/localhost/127\.0\.0\.2/g" $accs
    command: |
      echo "source $(pwd)/venv/bin/activate" >> ~/.bashrc
      source venv/bin/activate
image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
